services:
  postgres:
    image: postgres:17
    container_name: rpg-postgres

    environment:
      POSTGRES_DB: rpgdb
      POSTGRES_USER: rpguser
      POSTGRES_PASSWORD: rpgpass

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: backend/
    container_name: rpg-backend

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rpgdb
      SPRING_DATASOURCE_USERNAME: rpguser
      SPRING_DATASOURCE_PASSWORD: rpgpass

    depends_on:
      - postgres

  frontend:
    build: frontend/
    container_name: rpg-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

volumes:
  postgres_data: