services:
  postgres:
    image: postgres:17
    container_name: rpg-postgres

    environment:
      POSTGRES_DB: rpgdb
      POSTGRES_USER: rpguser
      POSTGRES_PASSWORD: rpgpass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: backend/
    container_name: rpg_backend

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rpgdb
      SPRING_DATASOURCE_USERNAME: rpguser
      SPRING_DATASOURCE_PASSWORD: rpgpass

    depends_on:
      - postgres

volumes:
  postgres_data: